# Generated by Django 3.0.4 on 2020-04-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(to='usersapp.User'),
        ),
    ]
